# Generated by Django 4.2.30 on 2026-04-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=80, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('telefon', models.CharField(max_length=15, verbose_name='Numer telefonu')),
                ('data_urodzenia', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('pesel', models.CharField(blank=True, help_text='Opcjonalnie', max_length=11, verbose_name='PESEL')),
                ('data_rejestracji', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pacjent',
                'verbose_name_plural': 'Pacjenci',
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.CreateModel(
            name='Specjalizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True, verbose_name='Nazwa specjalizacji')),
                ('opis', models.TextField(help_text='Krótki opis czym zajmuje się ta specjalizacja', verbose_name='Opis')),
                ('ikona_fa', models.CharField(default='fa-stethoscope', help_text='Np. fa-heart, fa-eye, fa-brain', max_length=60, verbose_name='Ikona Font Awesome')),
                ('kolor_karty', models.CharField(default='primary', help_text='Np. primary, success, danger, warning, info', max_length=20, verbose_name='Kolor Bootstrap')),
            ],
            options={
                'verbose_name': 'Specjalizacja',
                'verbose_name_plural': 'Specjalizacje',
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=60, verbose_name='Imię')),
                ('nazwisko', models.CharField(max_length=80, verbose_name='Nazwisko')),
                ('plec', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], default='M', max_length=1, verbose_name='Płeć')),
                ('tytul', models.CharField(default='lek. med.', help_text='Np. dr n. med., lek. med., prof. dr hab.', max_length=20, verbose_name='Tytuł')),
                ('doswiadczenie_lat', models.PositiveIntegerField(default=5, verbose_name='Lata doświadczenia')),
                ('opis', models.TextField(help_text='Krótki opis, wykształcenie, metody leczenia', verbose_name='O lekarzu')),
                ('ocena', models.DecimalField(decimal_places=1, default=4.5, max_digits=3, verbose_name='Ocena (1–5)')),
                ('liczba_opinii', models.PositiveIntegerField(default=0, verbose_name='Liczba opinii')),
                ('godz_pracy', models.CharField(choices=[('08:00-14:00', '08:00 – 14:00'), ('10:00-16:00', '10:00 – 16:00'), ('12:00-18:00', '12:00 – 18:00'), ('14:00-20:00', '14:00 – 20:00')], default='08:00-14:00', max_length=15, verbose_name='Godziny pracy')),
                ('dni_pracy', models.CharField(choices=[('12345', 'Poniedziałek – Piątek'), ('1234', 'Poniedziałek – Czwartek'), ('1235', 'Pon, Wt, Śr, Pt'), ('246', 'Wtorek, Czwartek, Sobota')], default='12345', max_length=10, verbose_name='Dni tygodnia')),
                ('czas_wizyty_min', models.PositiveIntegerField(default=30, help_text='Długość jednej wizyty w minutach (15, 20, 30, 45, 60)', verbose_name='Czas wizyty (minuty)')),
                ('nr_gabinetu', models.CharField(blank=True, max_length=10, verbose_name='Nr gabinetu')),
                ('miasto', models.CharField(default='Warszawa', max_length=80, verbose_name='Miasto')),
                ('adres', models.CharField(blank=True, max_length=200, verbose_name='Adres placówki')),
                ('cena_wizyty', models.DecimalField(decimal_places=2, default=150.0, max_digits=7, verbose_name='Cena wizyty (zł)')),
                ('aktywny', models.BooleanField(default=True, verbose_name='Profil aktywny')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('specjalizacja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lekarze', to='wizytownik.specjalizacja', verbose_name='Specjalizacja')),
            ],
            options={
                'verbose_name': 'Lekarz',
                'verbose_name_plural': 'Lekarze',
                'ordering': ['nazwisko', 'imie'],
            },
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data wizyty')),
                ('godzina', models.TimeField(verbose_name='Godzina wizyty')),
                ('status', models.CharField(choices=[('oczekujaca', 'Oczekująca'), ('potwierdzona', 'Potwierdzona'), ('odbyta', 'Odbyta'), ('anulowana', 'Anulowana')], default='oczekujaca', max_length=15, verbose_name='Status')),
                ('powod_wizyty', models.TextField(blank=True, help_text='Opcjonalny opis problemu', verbose_name='Powód wizyty / objawy')),
                ('notatki_lekarza', models.TextField(blank=True, verbose_name='Notatki lekarza (widoczne tylko dla personelu)')),
                ('data_rezerwacji', models.DateTimeField(auto_now_add=True, verbose_name='Data dokonania rezerwacji')),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizyty', to='wizytownik.lekarz', verbose_name='Lekarz')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizyty', to='wizytownik.pacjent', verbose_name='Pacjent')),
            ],
            options={
                'verbose_name': 'Wizyta',
                'verbose_name_plural': 'Wizyty',
                'ordering': ['data', 'godzina'],
                'unique_together': {('lekarz', 'data', 'godzina')},
            },
        ),
    ]
